export const services = [
  {
    id: 'service-01',
    slug: 'yol-yapimi',
    title: 'Yol Yapimi',
    tag: 'Ulasim Altyapisi',
    image: '/gallery/4.jpg',
    gallery: ['/gallery/4.jpg', '/gallery/5.jpg', '/gallery/9.jpg'],
    shortDescription:
      'Asfalt ve beton yol imalatlarinda kazidan ustyapiya kadar tum sureci planli saha organizasyonuyla yonetiyoruz.',
    fullDescription:
      'Yol yapimi hizmetimizde platform hazirligi, kazi ve dolgu, alt temel-serme, drenaj cozumleri, asfalt ya da beton kaplama ve trafik guvenligi kalemlerini tek akista yonetiyoruz. Erzurum iklimine ve saha kosullarina uygun uygulama programi hazirliyor; ekipman, malzeme ve sevkiyat koordinasyonunu ayni merkezden takip ediyoruz.',
    features: ['Kazi, dolgu ve zemin hazirligi', 'Alt temel ve ustyapi imalatlari', 'Asfalt ve beton yol uygulamasi', 'Trafik guvenligi ve saha yonetimi', 'Programli ekipman sevkiyati', 'Zamaninda teslim disiplini'],
    process: [
      { step: 'Kesif ve aplikasyon', desc: 'Guzergah, kot, zemin ve saha lojistigi analiz edilerek uygulama programi kurulur.' },
      { step: 'Kazi ve dolgu organizasyonu', desc: 'Kazi, nakliye, dolgu ve sikistirma surecleri makine parkina uygun sekilde yurutulur.' },
      { step: 'Kaplama ve guvenlik', desc: 'Asfalt ya da beton kaplama, kenar imalatlari ve trafik emniyetiyle teslim sureci tamamlanir.' },
    ],
  },
  {
    id: 'service-02',
    slug: 'beton-agrega',
    title: 'Beton Agrega',
    tag: 'Malzeme ve Lojistik',
    image: '/gallery/14.jpg',
    gallery: ['/gallery/14.jpg', '/gallery/8.jpg', '/gallery/15.jpg'],
    shortDescription:
      'Beton icin gerekli agrega tedarigi, stok sahasi yonetimi, kalite kontrol ve sevkiyat planlamasini sahaya uygun sekilde kuruyoruz.',
    fullDescription:
      'Beton ve agrega hizmetimizde ocaktan sahaya uzanan malzeme akisinin surekliligini sagliyoruz. Malzeme siniflandirmasi, stok sahasi duzeni, yukleme-plasman, sevkiyat plani ve saha ihtiyacina gore dozlu tedarik yapisiyla uygulama guvenligini arttiriyoruz. Uretim ve nakliye ritmini projedeki gunluk imalat hedefleriyle eslestiriyoruz.',
    features: ['Agrega temini ve saha stok yonetimi', 'Kalite kontrol ve uygun siniflandirma', 'Beton icin duzenli malzeme akisi', 'Sevkiyat ve kamyon planlamasi', 'Gunluk imalat hedeflerine uyum', 'Sahaya gore esnek lojistik model'],
    process: [
      { step: 'Malzeme analizi', desc: 'Proje ihtiyacina gore agrega sinifi, miktar ve teslim ritmi belirlenir.' },
      { step: 'Stok saha kurgusu', desc: 'Yukleme, bosaltma ve depolama alanlari verimli akisa gore organize edilir.' },
      { step: 'Sevkiyat takibi', desc: 'Gunluk saha ihtiyaci, arac planlamasi ve teslim kontrolu ayni tabloda yonetilir.' },
    ],
  },
  {
    id: 'service-03',
    slug: 'tunel-isleri',
    title: 'Tunel Isleri',
    tag: 'Kazi ve Destekleme',
    image: '/gallery/1.jpg',
    gallery: ['/gallery/1.jpg', '/gallery/11.jpg', '/gallery/12.jpg'],
    shortDescription: 'Tunel kazi, destekleme, drenaj ve saha guvenligi kalemlerini kontrollu ilerleme mantigiyla yonetiyoruz.',
    fullDescription:
      'Tunel islerinde kazi ritmi, kaya davranisi, destekleme sistemi, drenaj ve is guvenligi ayni anda yonetilmelidir. ME-KA Insaat, tunel portal hazirligi, mekanik kazi ya da delme-patlatma sonrasi destekleme, su yalitimi ve ic lojistik akisini planli saha koordinasyonuyla yurutur. Kritik noktalarda hizdan once kontrol ve guvenlik ilkesini esas aliriz.',
    features: ['Portal hazirligi ve kazi plani', 'Destekleme ve tahkimat koordinasyonu', 'Drenaj ve su yonetimi', 'Iceri lojistik ve ekipman akisi', 'Guvenlik standartlarina uyum', 'Kontrollu ve raporlanabilir ilerleme'],
    process: [
      { step: 'Jeolojik okuma ve planlama', desc: 'Kazinin davranisina gore ekipman, vardiya ve destekleme ritmi kurgulanir.' },
      { step: 'Kazi ve tahkimat', desc: 'Kazi ilerlerken anlik destekleme, drenaj ve stabilite adimlari birlikte uygulanir.' },
      { step: 'Ic lojistik ve kontrol', desc: 'Malzeme girisi, hafriyat cikisi, guvenlik ve gunluk saha raporlariyla surec kapatilir.' },
    ],
  },
  {
    id: 'service-04',
    slug: 'dere-islahi',
    title: 'Dere Islahi',
    tag: 'Su Yapilari',
    image: '/gallery/13.jpg',
    gallery: ['/gallery/13.jpg', '/gallery/1.jpg', '/gallery/2.jpg'],
    shortDescription: 'Erozyon kontrolu, tas tahkimat, menfez ve yatak duzenleme kalemleriyle dere islahini uygulama sahasina uygun cozumlerle yurutuyoruz.',
    fullDescription:
      'Dere islahinda esas konu sadece akis kesitini duzenlemek degil, sahayi uzun vadeli olarak koruyacak bir yapi kurmaktir. Tas tahkimat, gabion, sedde, menfez baglantilari ve yatak duzenleme imalatlarini arazi ve su rejimine gore planliyoruz. Cevreye uyumlu ve bakimi kolay cozumleri saha kosullarina gore uyguluyoruz.',
    features: ['Erozyon kontrolu ve tahkimat', 'Gabion, tas duvar ve sedde imalatlari', 'Menfez ve gecis yapilari', 'Yatak duzenleme ve guclendirme', 'Agir ekipman saha koordinasyonu', 'Cevresel etkiye duyarli uygulama'],
    process: [
      { step: 'Arazi ve akis analizi', desc: 'Dere kesiti, zemin davranisi ve su yukleri degerlendirilir.' },
      { step: 'Yapi ve tahkimat uygulamasi', desc: 'Tas, gabion, menfez ve koruma elemanlari proje siralamasina gore uygulanir.' },
      { step: 'Son kontrol ve temizlik', desc: 'Akis surekliligi, kenar guvenligi ve saha duzeni teslim oncesi kontrol edilir.' },
    ],
  },
  {
    id: 'service-05',
    slug: 'tas-isleri',
    title: 'Tas Isleri',
    tag: 'Tahkimat ve Peyzaj',
    image: '/gallery/7.jpg',
    gallery: ['/gallery/7.jpg', '/gallery/3.jpg', '/gallery/13.jpg'],
    shortDescription: 'Tas duvar, tahkimat, ocak ici kirma ve saha duzenleme uygulamalarini dayanikli ve temiz bir iscilikle gerceklestiriyoruz.',
    fullDescription:
      'Tas islerinde saha kosullarina uygun tas secimi, uygulama detayi ve iscilik kalitesi belirleyicidir. Tahkimat duvarlari, tas kaplama, duzenleme ve dekoratif ya da fonksiyonel tas uygulamalarini agir makine destegiyle yurutuyoruz. Dayaniklilik, duzgun gorunum ve uzun omur icin zemin hazirligini ve su yonetimini birlikte dusunuyoruz.',
    features: ['Tas duvar ve tahkimat imalatlari', 'Ocak ici tas kirma ve siniflama', 'Peyzaj ve saha duzenleme taslari', 'Yamac guclendirme uygulamalari', 'Uzun omurlu detay cozumleri', 'Temiz ve duzgun iscilik'],
    process: [
      { step: 'Kesit ve detay karari', desc: 'Yapinin yuk tasima ihtiyaci ve gorunur yuz detaylari belirlenir.' },
      { step: 'Tas hazirligi ve uygulama', desc: 'Tas secimi, kirma, yerlestirme ve baglayici sistemle uygulama sahada yonetilir.' },
      { step: 'Koruma ve son kontrol', desc: 'Yuzey duzeni, drenaj ve deformasyon riskleri teslim oncesi gozden gecirilir.' },
    ],
  },
  {
    id: 'service-06',
    slug: 'beton-bordur-kaldirim',
    title: 'Beton Bordur ve Kaldirim',
    tag: 'Sehircilik Uygulamalari',
    image: '/gallery/10.jpg',
    gallery: ['/gallery/10.jpg', '/gallery/9.jpg', '/gallery/5.jpg'],
    shortDescription: 'Bordur, kaldirim ve yaya yolu uygulamalarinda duzgun hat, dayanikli beton ve guvenli detaylar uzerine calisiyoruz.',
    fullDescription:
      'Beton bordur ve kaldirim islerinde yalnizca imalat hizi degil, hat duzeni, kot dogrulugu ve dayaniklilik da belirleyicidir. Yaya yolu, yol kenari borduru, ada ve gecis detaylarini saha akisina uygun planliyoruz. Beton kalitesi, alt zemin hazirligi ve trafik guvenligini birlikte ele alarak sehir ici uygulamalarda temiz bir teslim sagliyoruz.',
    features: ['Yaya yolu ve kaldirim imalatlari', 'Beton bordur ve ada detaylari', 'Kot ve hat kontrolu', 'Alt zemin hazirligi ve sikistirma', 'Sehir ici trafik guvenligi', 'Temiz teslim ve saha toparlama'],
    process: [
      { step: 'Olcu ve hat hazirligi', desc: 'Aplikasyon, kot ve hat duzeni saha basinda netlestirilir.' },
      { step: 'Beton ve bordur uygulamasi', desc: 'Alt zemin hazirligi tamamlanir, beton ve bordur imalatlari kontrollu sekilde uygulanir.' },
      { step: 'Duzenleme ve teslim', desc: 'Yuruyus guvenligi, kenarlar, derzler ve genel gorunum teslim oncesi son kez kontrol edilir.' },
    ],
  },
  {
    id: 'service-07',
    slug: 'buyuk-altyapi-projeleri',
    title: 'A5 A9 A19 B3 Altyapi Projeleri',
    tag: 'Benzer Is Deneyimi',
    image: '/gallery/2.jpg',
    gallery: ['/gallery/2.jpg', '/gallery/6.jpg', '/gallery/15.jpg'],
    shortDescription: 'Karayolu, saha duzenleme, menfez, kazi-dolgu ve buyuk olcekli uygulamalari A5, A9, A19 ve B3 kapsamli saha refleksiyle yonetiyoruz.',
    fullDescription:
      'Buyuk altyapi projelerinde is kalemleri birbiriyle baglantili yurur: yol, drenaj, menfez, tas tahkimat, saha lojistigi, beton ve malzeme akisi ayni anda koordine edilir. ME-KA Insaat; A5, A9, A19 ve B3 olarak ifade edilen buyuk is gruplarina uygun saha disiplini, ekipman plani ve teslim kontroluyle hareket eder. Ihale sonrasi sahayi hizli kurar, uygulama surecini raporlanabilir sekilde takip ederiz.',
    features: ['Karayolu ve saha platform imalatlari', 'Menfez, drenaj ve yardimci yapilar', 'Kazi-dolgu ve agir ekipman koordinasyonu', 'Beton, agrega ve demir planlamasi', 'Ihale sonrasi hizli saha kurulumu', 'Raporlu ilerleme ve teslim takibi'],
    process: [
      { step: 'Ihale sonrasi saha kurulumu', desc: 'Makine, ekip, tedarik ve saha yerlesimi uygulamaya uygun sekilde hizla kurulur.' },
      { step: 'Es zamanli imalat yonetimi', desc: 'Yol, su yapisi, tas, beton ve lojistik kalemleri tek bir program uzerinden ilerletilir.' },
      { step: 'Kontrol ve teslim', desc: 'Metraj, kalite, sure ve saha kapanisi teslim disiplinine gore tamamlanir.' },
    ],
  },
]

export const projects = [
  {
    id: 'erzurum-yol-yapimi',
    title: 'Erzurum Yol Yapimi, Asfalt ve Altyapi Uygulamasi',
    category: 'Yol',
    location: 'Erzurum',
    year: '2024',
    area: 'Erzurum yol yapimi, asfalt ve saha duzeni',
    duration: '8 ay',
    coverImage: '/gallery/4.jpg',
    images: ['/gallery/4.jpg', '/gallery/5.jpg', '/gallery/9.jpg'],
    description: 'Erzurum yol yapimi, kazi-dolgu, temel hazirligi ve asfalt serimi adimlarini ayni saha planinda birlestiren ulasim odakli proje.',
    fullDescription: 'Bu Erzurum yol yapimi projesinde guzergah hazirligi, dolgu ve sikistirma, yol alt yapisi, plentmiks temel ve asfalt serimi birlikte planlandi. Gorselde gorulen genis saha duzeni, agir ekipman akisi ve malzeme sevkiyati tek merkezden yonetilerek yol yapimi sureci kontrollu, guvenli ve zamaninda ilerletildi.',
    highlights: ['Erzurum yol yapimi ve kazi-dolgu organizasyonu', 'Asfalt serim ve plent koordinasyonu', 'Yol kenari duzenleme ve trafik guvenligi', 'Saha ekipman ve malzeme plani'],
  },
  {
    id: 'tunel-kazi-destekleme',
    title: 'Erzurum Tunel Kazi ve Destekleme Calismasi',
    category: 'Tunel',
    location: 'Erzurum',
    year: '2023',
    area: 'Tunel kazisi, tahkimat ve saha guvenligi',
    duration: '11 ay',
    coverImage: '/gallery/1.jpg',
    images: ['/gallery/1.jpg', '/gallery/11.jpg', '/gallery/12.jpg'],
    description: 'Erzurum tunel kazi projesinde portal hazirligi, destekleme, tahkimat ve ic lojistik kontrollu bir uygulama akisi ile yurutuldu.',
    fullDescription: 'Tunel sahasinda portal bolgesi kurulumu, kontrollu kazi ilerleyisi, tahkimat uygulamalari ve su yonetimi ayni disiplin icinde ele alindi. Gorsellerle uyumlu olarak dar alan lojistigi, hafriyat cikisi ve saha guvenligi raporlanabilir bir sistemle yonetildi; bu da Erzurum tunel kazi ve destekleme islerinde sureklilik sagladi.',
    highlights: ['Tunel portali ve giris alani kurulumu', 'Tahkimat ve destekleme koordinasyonu', 'Ic lojistik ve hafriyat cikisi plani', 'Guvenlik odakli tunel saha kontrolu'],
  },
  {
    id: 'agrega-ve-beton-lojistik',
    title: 'Erzurum Agrega Uretim ve Beton Lojistik Sahasi',
    category: 'Agrega',
    location: 'Erzurum',
    year: '2024',
    area: 'Erzurum agrega, stok ve beton sevkiyat',
    duration: 'Devam ediyor',
    coverImage: '/gallery/14.jpg',
    images: ['/gallery/14.jpg', '/gallery/8.jpg', '/gallery/15.jpg'],
    description: 'Erzurum agrega uretimi, kirma-eleme, stok saha yonetimi ve beton lojistigini ayni duzende bulusturan malzeme odakli operasyon.',
    fullDescription: 'Bu projede Erzurum agrega uretimi, siniflandirma, stok alanlari, yukleme duzeni ve beton sevkiyat plani gunluk uygulama ihtiyacina gore kuruldu. Gorseldeki saha yapisina uygun olarak kamyon hareketi, stok kontrolu ve beton icin surekli malzeme akisi ayni sistem icinde yonetilerek zaman ve saha kaybi azaltildi.',
    highlights: ['Kirma-eleme ve agrega stok saha kurgusu', 'Kamyon ve sevkiyat planlamasi', 'Beton icin surekli malzeme akisi', 'Gunluk uretim ve tuketim takibi'],
  },
  {
    id: 'dere-islahi-ve-tahkimat',
    title: 'Erzurum Dere Islahi ve Tas Tahkimat Uygulamasi',
    category: 'Su Yapilari',
    location: 'Yakutiye / Erzurum',
    year: '2022',
    area: 'Dere islahi, tas tahkimat ve akis guvenligi',
    duration: '6 ay',
    coverImage: '/gallery/13.jpg',
    images: ['/gallery/13.jpg', '/gallery/1.jpg', '/gallery/2.jpg'],
    description: 'Erzurum dere islahi projesinde tas tahkimat, gabion duvar ve akis yonetimi cozumleriyle guclu saha korumasi saglandi.',
    fullDescription: 'Erozyon riskinin yuksek oldugu bu Erzurum dere islahi uygulamasinda yatak duzenleme, gabion, tas tahkimat ve baglanti yapilari sahaya gore planlandi. Gorsellerdeki arazi yapisina uygun olarak akis guvenligi, saha erisimi ve agir ekipman kullanimi birlikte degerlendirilerek uzun omurlu su yapisi cozumleri uretilmistir.',
    highlights: ['Gabion ve tas tahkimat imalatlari', 'Dere yatagi duzenleme ve koruma cozumleri', 'Agir ekipman ile kontrollu saha girisi', 'Uzun omurlu su yapisi disiplini'],
  },
  {
    id: 'bordur-ve-kaldirim',
    title: 'Erzurum Beton Bordur ve Kaldirim Uygulamasi',
    category: 'Sehircilik',
    location: 'Erzurum Merkez',
    year: '2023',
    area: 'Beton bordur, kaldirim ve yaya yolu',
    duration: '4 ay',
    coverImage: '/gallery/10.jpg',
    images: ['/gallery/10.jpg', '/gallery/9.jpg', '/gallery/5.jpg'],
    description: 'Erzurum beton bordur ve kaldirim uygulamasinda yaya yolu, kot duzeni ve kent ici guvenlik oncelikli saha yonetimi uygulandi.',
    fullDescription: 'Bu projede yaya yolu duzeni, bordur hatlari, kot kontrolu ve beton kalitesi birlikte ele alindi. Gorseldeki kent ici uygulama yapisina uygun olarak etapli saha yonetimi kurulmus, sehir trafigi aksamadan beton bordur ve kaldirim imalatlari temiz teslim hedefiyle tamamlanmistir.',
    highlights: ['Hat ve kot kontrolu', 'Beton bordur ve kaldirim imalati', 'Etapli sehir ici saha yonetimi', 'Temiz teslim ve son duzenleme'],
  },
  {
    id: 'a5-a9-a19-b3-altyapi',
    title: 'Erzurum A5 A9 A19 B3 Kapsamli Altyapi Organizasyonu',
    category: 'Buyuk Altyapi',
    location: 'Erzurum ve cevresi',
    year: '2024',
    area: 'Karayolu, beton, agrega ve yardimci yapilar',
    duration: '12 ay',
    coverImage: '/gallery/2.jpg',
    images: ['/gallery/2.jpg', '/gallery/6.jpg', '/gallery/15.jpg'],
    description: 'Erzurum buyuk altyapi sahasinda yol, kazi, beton, menfez ve agrega lojistigini ayni programla yoneten kapsamli saha organizasyonu.',
    fullDescription: 'Genis sahaya yayilan bu Erzurum altyapi projesinde kazi-dolgu, yol platformu, yardimci beton imalatlari, menfez calismalari, agrega tedarigi ve ekipman yerlesimi tek merkezli koordinasyonla ilerletildi. Gorsellerdeki buyuk saha olcegine uygun olarak A5, A9, A19 ve B3 benzer is disipliniyle planli, raporlu ve teslim odakli bir uygulama modeli benimsendi.',
    highlights: ['Es zamanli kazi, dolgu ve yol platformu yonetimi', 'Beton, agrega ve saha lojistik koordinasyonu', 'Menfez ve yardimci yapi kalemleri', 'Program odakli buyuk saha teslimi'],
  },
]

export const serviceBySlug = Object.fromEntries(services.map((service) => [service.slug, service]))
export const projectById = Object.fromEntries(projects.map((project) => [project.id, project]))
